name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Medias
        if: ${{ success() || failure() }}
        uses: data-igor/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: anilist, music
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.METRICS_TOKEN }}
          plugin_music_limit: 9

      - name: Achievements
        if: ${{ success() || failure() }}
        uses: data-igor/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      - name: General
        if: ${{ success() || failure() }}
        uses: data-igor/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes
          
      - name: Splatoon
        uses: data-igor/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: splatoon.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          plugin_splatoon: yes
          plugin_splatoon_token: ${{ secrets.METRICS_TOKEN }}
          plugin_splatoon_statink: yes
          plugin_splatoon_statink_token: ${{ secrets.METRICS_TOKEN }}
          plugin_splatoon_sections: salmon-run
          plugin_splatoon_salmon_limit: 2
          extras_css: |
            h2 { display: none !important; }
            .match:not(:last-child) { padding-bottom: 4px; }
