name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  # and on each push
  push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Achievements
        if: ${{ success() || failure() }}
        uses: stalomeow/metrics@projects-v2 # lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
          config_order: base.header, isocalendar, achievements
          committer_gist: ${{ secrets.METRICS_TOKEN }}

